// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: Guid("c967e749-c20b-4225-abdd-af9297e6414f")]
[assembly: CLSCompliant(true)]
[assembly: InternalsVisibleTo("MurMurHashAlgorithm.Tests")]
